[package]
name = "jsonapi"
version = "0.1.0"
authors = ["Michiel Kalkman <michiel@nosuchtype.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.8"

[dependencies]
serde = "0.8"
serde_json = "0.8"
